name: 'Commit information action'
description: 'Get the checked out commit information'
author: 'Rémi DEBETTE'
inputs:
  GITHUB_SHA:
    description: 'SHA Hash of the current commit information'
    default: ''
outputs:
  GITHUB_ONELINE:
    description: 'Oneline git description of the commit. Available as an Environment variable'
  BUILD_URL:
    description: 'A variable for accessing the current build screen'
runs:
  using: 'node12'
  main: 'lib/main.js'
